### ISSUE TITLE
packages are not updated when already installed

### ISSUE THREAD

**Issue by wasrek404** [jffz/ansible-netdata#21]
I think this task:

```
- name: install pre-requisites
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ netdata_script_dependencies }}"
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2
```

The 'state' part shouldn't be present but latest like so: 

```
- name: install pre-requisites
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ netdata_script_dependencies }}"
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2
```

I noticed this when running your role on a host that already had all software installed just not the latest version. Reinstalling the dependencies manually on the host with apt solved all the issues I had with this role. Can you adapt the role so it updates the dependencies when updating/installing? 

Thanks for the role, I use it a lot!
